"""db_user_rating

Revision ID: 02572a0874f4
Revises: 84fbee80a603
Create Date: 2026-08-30 04:46:39.547467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02572a0874f4"
down_revision: Union[str, Sequence[str], None] = "84fbee80a603"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_ratings",
        sa.Column("flashcard_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Enum("EASY", "MEDIUM", "HARD", name="rating_enum"), nullable=False),
        sa.ForeignKeyConstraint(
            ["flashcard_id"],
            ["flashcards.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("flashcard_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_ratings")
    # ### end Alembic commands ###
