"""db_flashcard

Revision ID: 9edf069c3e50
Revises: 67a47fa150b8
Create Date: 2026-07-18 06:57:01.926480

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9edf069c3e50"
down_revision: Union[str, Sequence[str], None] = "67a47fa150b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flashcards",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("word", sa.String(length=120), nullable=False),
        sa.Column("meaning", sa.String(length=500), nullable=False),
        sa.Column(
            "part_of_speech",
            sa.Enum(
                "NOUN",
                "VERB",
                "ADJECTIVE",
                "ADVERB",
                "PRONOUN",
                "PREPOSITION",
                "CONJUNCTION",
                "INTERJECTION",
                name="part_of_speech_enum",
            ),
            nullable=False,
        ),
        sa.Column("example", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("word"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flashcards")
    # ### end Alembic commands ###
