# command:
#   - bash
#   - -c
#   - |
#     export PATH="$(pwd)/.venv/bin:$PATH"
#     cd src
#     uvicorn main:app --host 0.0.0.0 --port $DATABRICKS_APP_PORT

command:
- bash
- -c
- |
  env | sort
  sleep 300

#   alembic upgrade head && \

env:
  - name: PYTHONUNBUFFERED
    value: "1"