command:
  - bash
  - -c
  - |
    pwd
    ls -la
    cd src
    which python
    python --version
    python -m uvicorn --version
    uvicorn src.main:app --host 0.0.0.0 --port $DATABRICKS_APP_PORT

#   alembic upgrade head && \

env:
  - name: PYTHONUNBUFFERED
    value: "1"